homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_alt
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize: !include customize.yaml
  customize_glob:
    light.*:
      custom_ui_state_card: state-card-custom-ui
      state_card_mode: break-slider
      stretch_slider: true
      slider_theme:
        min: 5
        off_when_min: false


# Enables the frontend
frontend:
  themes: !include_dir_named themes/

customizer:
  custom_ui: local

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

recorder:
  purge_days: 7

# Discover some devices automatically
discovery:
  ignore:
    - plex_mediaserver

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

logger:
  default: warn

# Track the sun
sun:

zwave:
  usb_path: /dev/ttyUSB0

zha:
  usb_path: /dev/ttyUSB1
  database_path: /config/zigbee.db

sensor:
  - platform: darksky
    api_key: !secret weather_key
    name: Weather
    monitored_conditions:
     - summary
     - apparent_temperature
     - apparent_temperature_max
     - precip_type
    update_interval: '00:10'
  - platform: speedtest
    monitored_conditions:
     - ping
     - download
     - upload
  - platform: snmp
    host: !secret desktopdave_ip
    name: desktopdave_snmp
    baseoid: 1.3.6.1.2.1.1.5.0
    version: 2c
  - platform: template
    sensors:
      desktopdave:
        friendly_name: "Dave's Desktop"
        value_template: "{% if is_state('sensor.desktopdave_snmp', 'desktop-dave') %}System Up{% else %}System Offline{% endif %}"

# Text to speech
tts:
  platform: google

group: !include groups.yaml

device_tracker:
  - platform: ddwrt
    host: !secret router_ip
    username: !secret router_user
    password: !secret router_pass
    track_new_devices: no
    consider_home: 60
  - platform: bluetooth_tracker
    track_new_devices: no

notify:
  - name: slack
    platform: slack
    api_key: !secret slack_key
    default_channel: !secret slack_channel

input_boolean:
  rocky_fed:
    name: Rocky Ate
    initial: off
    icon: mdi:cat
  sleep_mode:
    name: Sleep Mode
    icon: mdi:hotel

switch:
  - platform: flux
    lights:
      - light.david__dresser
    name: Flux
    start_time: '6:00'
    stop_time: '22:00'
    stop_colortemp: 2200
    disable_brightness_adjust: True
  - platform: wake_on_lan
    name: "Wake Dave's Desktop"
    mac_address: !secret desktopdave_mac
    host: !secret desktopdave_ip

automation: !include_dir_merge_list automation/

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

input_select:
  pcoptions:
    name: PC Power Options
    options:
      - None
      - Sleep 
      - Shutdown
    initial: None
    icon: mdi:desktop-tower

shell_command:
  shutdown_desktopdave: !secret desktopdave_shutdown
  sleep_desktopdave: !secret desktopdave_suspend

script: !include_dir_named script/ 

mysensors:
  gateways:
    - device: '/dev/ttyUSB2'
      persistence_file: '/home/homeassistant/.homeassistant/mysensors.json'
      baud_rate: 115200
  version: 2.0
