homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_alt
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize:
    group.all_lights:
      friendly_name: Lights
      hidden: false
    group.all_automations:
      friendly_name: Automation
      hidden: false


# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: darksky
  api_key: !secret weather_key
  name: Weather
  monitored_conditions:
   - summary
   - apparent_temperature
   - apparent_temperature_max
   - precip_type
  update_interval: '00:10'

# Text to speech
tts:
  platform: google

group: !include groups.yaml

device_tracker:
  - platform: ddwrt
    host: !secret router_ip
    username: !secret router_user
    password: !secret router_pass
    track_new_devices: yes

notify:
  - name: slack
    platform: slack
    api_key: !secret slack_key
    default_channel: !secret slack_channel

input_boolean:
  rocky_fed:
    name: Rocky Ate
    initial: off
    icon: mdi:cat

switch:
  platform: flux
  lights:
    - light.david__dresser
  name: Flux
  start_time: '6:00'
  stop_time: '22:00'
  disable_brightness_adjust: True

automation: !include_dir_merge_list automation/

