- alias: Turn on master bedroom lights at sunset
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 3.0
  action:
    service: light.turn_on
    data:
      entity_id: group.lights_master
      transition: 180
      brightness: 255

- alias: Turn off master bedroom lights during the day when no one's home
  trigger:
    platform: state
    entity_id: group.person_dave, group.person_lauren
    from: 'home'
    to: 'not_home'
  condition:
    condition: sun
    after: sunrise
    before: sunset
    before_offset: "-01:00:00"
  action:
    service: light.turn_off
    data:
      entity_id: group.lights_master

- alias: Turn on living room lights at night when motion is detected
  trigger:
    platform: state
    entity_id: binary_sensor.livingmotion_sensor
    to: 'on'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    service: light.turn_on
    data_template:
      entity_id: group.lights_living
      transition: 3
      brightness: >
        {% if is_state('input_boolean.sleep_mode', 'on') %}
          1
        {% else %}
          {{ 200 - (states("sensor.light_sensor_2_1")) | int }}
        {% endif %}

- alias: Turn off living room lights during sleep mode when no motion detected
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: binary_sensor.livingmotion_sensor
    to: 'off'
  action:
    service: light.turn_off
    data:
      entity_id: group.lights_living
      transition: 5

- alias: Turn off the living room lights when no motion is detected
  trigger:
    platform: state
    entity_id: binary_sensor.livingmotion_sensor
    to: 'off'
    for:
      minutes: 11
  action:
    service: light.turn_off
    data:
      entity_id: group.lights_living
      transition: 2
