- alias: Turn off master bedroom lights during the day when no one's home
  trigger:
    platform: state
    entity_id: group.person_dave, group.person_lauren
    from: 'home'
    to: 'not_home'
  condition:
    condition: sun
    after: sunrise
    before: sunset
    before_offset: "-01:00:00"
  action:
    service: light.turn_off
    data:
      entity_id: light.master_bedroom

- alias: Turn on living room lights at night when motion is detected
  trigger:
    platform: state
    entity_id: binary_sensor.livingmotion_sensor
    to: 'on'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    service: light.turn_on
    data_template:
      entity_id: light.living_room
      transition: 3
      brightness: >
        {% if is_state('input_boolean.sleep_mode', 'on') %}
          1
        {% else %}
          200
        {% endif %}

- alias: Turn on bedroom lights based on brightness
  trigger:
    platform: numeric_state
    entity_id: sensor.master_light_1
    below: 41
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: 'group.person_dave'
        state: 'home'
      - condition: state
        entity_id: 'group.person_lauren'
        state: 'home'

  action:
    service: light.turn_on
    data_template:
      entity_id: light.master_bedroom
      transition: 2
      brightness_pct: >
        {{ 100 - trigger.to_state.state|int }} 

- alias: Turn off living room lights during sleep mode when no motion detected
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: binary_sensor.livingmotion_sensor
    to: 'off'
  action:
    service: light.turn_off
    data:
      entity_id: light.living_room
      transition: 5

- alias: Turn off the living room lights when no motion is detected
  trigger:
    platform: state
    entity_id: binary_sensor.livingmotion_sensor
    to: 'off'
    for:
      minutes: 11
  action:
    service: light.turn_off
    data:
      entity_id: light.living_room
      transition: 2

- alias: Turn off bedroom lights based on brightness
  trigger:
    platform: numeric_state
    entity_id: sensor.master_light_1
    above: 45
  action:
    service: light.turn_off
    data:
      entity_id: light.master_bedroom
      transition: 2

- alias: Turn on master bedroom lights before sunset
  trigger:
    platform: sun
    event: sunset
    offset: '-00:60:00'
  action:
    service: light.turn_on
    data:
      entity_id: light.master_bedroom
      transition: 2
      brightness_pct: 100

