- alias: Turn on Dave's lights at sunset when he's home
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 2.0
  action:
    service: light.turn_on
    data:
      entity_id: group.lights_dave
      transition: 3600
      brightness: 255

- alias: Turn off Dave's lights during the day when he leaves
  trigger:
    platform: state
    entity_id: group.person_dave
    from: 'home'
    to: 'not_home'
  condition:
    condition: sun
    after: sunrise
    before: sunset
    before_offset: "-01:00:00"
  action:
    service: light.turn_off
    data:
      entity_id: group.lights_dave

