- alias: Turn on master bedroom lights at sunset
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 3.0
  action:
    service: light.turn_on
    data:
      entity_id: group.lights_master
      transition: 1800
      brightness: 255

- alias: Turn off master bedroom lights during the day when no one's home
  trigger:
    platform: state
    entity_id: group.person_dave
    from: 'home'
    to: 'not_home'
  condition:
    condition: sun
    after: sunrise
    before: sunset
    before_offset: "-01:00:00"
  action:
    service: light.turn_off
    data:
      entity_id: group.lights_master

