- alias: Notify Slack when changing PC power state
  trigger:
    platform: state
    entity_id: input_select.pcoptions
    from: 'None'
  action:
    service: notify.slack
    data_template:
      message: 'PC has been set to suspend/shutdown'

- alias: 'Notify Slack when a HASS update is available'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.slack
    data:
      message: 'Update for Home Assistant is available.'

- alias: 'Notify Slack when motion sensor cover is opened'
  trigger:
    platform: state
    entity_id: sensor.livingmotion_burglar
    to: '3'
  action:
    service: notify.slack
    data:
      message: 'ALERT: Living room motion sensor is being tampered with!'

- alias: 'Notify Slack when motion sensor cover is closed'
  trigger:
    platform: state
    entity_id: sensor.livingmotion_burglar
    from: '3'
  action:
    service: notify.slack
    data:
      message: 'CLEAR: Living room motion sensor is being tampered with'

- alias: Notify Slack when Home Assistant has restarted
  hide_entity: True
  trigger:
    platform: homeassistant
    event: start
  action:
    service: notify.slack
    data:
      message: 'Home Assistant has been restarted'

- alias: 'Notify Slack when kitchen light has been left on and no motion detected'
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_multi_2
    to: 'off'
    for:
      minutes: 5
  condition:
    condition: state
    entity_id: binary_sensor.kitchen_light_1
    state: 'on'
  action:
    service: notify.slack
    data:
      message: 'Someone left the kitchen light on!'
